### PR TITLE
Scrum 168 frontend code quality check

### PR DESCRIPTION
**Pull request by chungchihhan**
## Description

原先的程式碼沒有code formatter跟lint check，加上來維護程式碼品質，並且透過github action來自動化步驟

## Type of Change

- [ ] 🐛 Bug Fix（修復 bug）
- [ ] ✨ New Feature（新功能）
- [ ] 💄 UI/UX（介面或使用者體驗優化）
- [x] 🔨 Refactor（程式碼重構）
- [ ] 📝 Documentation（文件更新）
- [ ] 🔧 Configuration（配置變更）
- [ ] 🚀 Performance（效能優化）
- [ ] ✅ Test（測試相關）
- [ ] 🔒 Security（安全性相關）

## Related Issues

[SCRUM-168](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-168)

## Testing

- [X] 完成測試 : 可以`npm run lint`測試

## Screenshots/Videos
image

## Checklist

- [x] 我已經測試過這些變更
- [ ] 我已經更新相關文件
- [x] 我的程式碼遵循專案的程式碼規範
- [x] 我已經處理所有的 console warnings/errors
- [x] 我已經移除所有的 console.log
- [ ] 我已經新增必要的測試案例
- [x] 所有現有的測試都能通過

## Additional Notes

[SCRUM-168]: https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by poyang1024** [comment]
@chungchihhan  是之後 push code 的時候會用 npm run lint 測試對嗎
那如果測試後有需要 formatter 的內容會需要跑什麼？還是他會自動 format

**Comment by chungchihhan** [comment]
Hi Tony !

### (OPTIONAL)
You can install Prettier extension in your VScode, which is recommended. Here are some steps for you to know : 
#### Install the Prettier extension:
1. Open VSCode.
2. Go to Extensions (Ctrl + Shift + X or Cmd + Shift + X on macOS).
3. Search for “Prettier - Code Formatter” and install it.
#### Set Prettier as the default formatter:
1.  Open your VSCode settings (Ctrl + , or Cmd + , on macOS).
2. Search for default formatter and set it to “Prettier - Code Formatter.”
3. Enable format on save by searching for editor.formatOnSave in settings and checking the box.

### Required
Here are the required steps for you to do: 
- For code format : 
  ```
  npm run format
  ```
  image

- For lint check : 
  ```
  npm run lint
  ```
  image

- If you want to do code format and lint check at the same time: 
  ```
  npm run fix
  ```
  image

### Make sure *ALL THE CHECKS HAVE PASSED* after you create a pull request
image

**Comment by poyang1024** [comment]
Okay LGTM!!

Memo：I think we can add the instructions into our Notion, making everyone know how to use formatter before they push the code, or we can add the formatter into pre-commit or pre-push after.

But now it's acceptable for this issue.

**Review by poyang1024 — APPROVED** [review]
LGTM!

**Pull request merged**
